#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Schlumberger 油藏模拟器自动识别与 License 验证工具
===================================================

自动检测本机安装的 Petrel、ECLIPSE 100、ECLIPSE 300、Intersect、
FrontSim、Visage 等 Schlumberger 油藏模拟器的位置和版本，
并验证 license 状态（环境变量、lmutil lmstat、最小测试案例三道关卡）。

设计原则：
1. 三层检索兜底 —— 注册表 → 常见路径 → 文件系统深度递归
2. 多维度 license 验证 —— 环境变量 → lmutil → smoke test
3. 适配不同设备 —— 路径、版本、架构可变，规则可扩展
4. 零外部依赖 —— 仅用 Python 标准库

用法:
    python simulator_detector.py                  # 标准检测（含 smoke test）
    python simulator_detector.py --deep           # 全盘深度搜索（慢）
    python simulator_detector.py --no-smoke       # 跳过 smoke test
    python simulator_detector.py --json           # 输出 JSON 到终端
    python simulator_detector.py --out <dir>      # 指定报告输出目录
    python simulator_detector.py -v               # 详细模式

作者: Buddy
日期: 2026-07-20
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import platform
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional, List, Dict, Set

try:
    import winreg
except ImportError:
    winreg = None  # 非 Windows 平台


# ============================================================
# 常量定义
# ============================================================

# 目标可执行文件名（小写）
TARGET_EXE_NAMES: Set[str] = {
    'eclipse.exe', 'eclipse_msmpi.exe',
    'e300.exe', 'e300_msmpi.exe',
    'intersect.exe', 'ix.exe',
    'frontsim.exe',
    'visage.exe',
    'petrel.exe', 'petrel_b.exe',
    'eclrun.exe',
}

# 产品识别规则：(exe 名正则, 产品代号)
PRODUCT_RULES = [
    (re.compile(r'^eclipse(_msmpi)?\.exe$', re.I), 'ECLIPSE_100'),
    (re.compile(r'^e300(_msmpi)?\.exe$', re.I),    'ECLIPSE_300'),
    (re.compile(r'^intersect\.exe$', re.I),         'INTERSECT'),
    (re.compile(r'^ix\.exe$', re.I),                 'INTERSECT'),
    (re.compile(r'^frontsim\.exe$', re.I),           'FRONTSIM'),
    (re.compile(r'^visage\.exe$', re.I),            'VISAGE'),
    (re.compile(r'^petrel(_b)?\.exe$', re.I),       'PETREL'),
    (re.compile(r'^eclrun\.exe$', re.I),            'ECLRUN'),
]

# 常见安装根目录（按优先级，越靠前越优先）
COMMON_INSTALL_ROOTS: List[str] = [
    r"C:\ecl",
    r"C:\SLB",
    r"C:\Schlumberger",
    r"C:\Petrel",
    r"C:\Program Files\Schlumberger",
    r"C:\Program Files (x86)\Schlumberger",
    r"C:\Program Files\Petrel",
    r"C:\Program Files (x86)\Petrel",
    r"D:\Schlumberger",
    r"D:\Petrel",
    r"D:\ecl",
    r"D:\SLB",
    r"E:\Schlumberger",
    r"E:\ecl",
]

# License 相关环境变量
LICENSE_ENV_VARS: List[str] = [
    'SLBSLS_LICENSE_FILE',   # Schlumberger 新版
    'SLBSLS_HOME',
    'FLEXLM_LICENSE_FILE',  # FlexNet 通用
    'LM_LICENSE_FILE',
    'LSERV_HOST',           # 部分老版
    'ECLIPSE_LICENSE_FILE',
]

# 注册表已安装程序查询键
REGISTRY_UNINSTALL_KEYS = [
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall") if winreg else None,
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall") if winreg else None,
    (winreg.HKEY_CURRENT_USER, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall") if winreg else None,
]
REGISTRY_UNINSTALL_KEYS = [k for k in REGISTRY_UNINSTALL_KEYS if k is not None]

# 注册表匹配关键字
REGISTRY_NAME_PATTERN = re.compile(
    r'eclipse|petrel|schlumberger|intersect|frontsim|visage|\becl\b|slb',
    re.I
)

# 版本号正则（如 2022.2 / 2022.1 / 2019.3）
VERSION_PATTERN = re.compile(r'^(\d{4}\.\d+)$')

# .PRT 文件中的版本提取正则
PRT_VERSION_PATTERN = re.compile(
    r'(?:Schlumberger\s+)?(?:ECLIPSE|E300|INTERSECT|FrontSim|VISAGE)\s+([\d.]+)\s*'
    r'(?:\(Build\s+([\d.]+)\)\s*)?(?:\(?(\d+\s*bit)?\)?)?',
    re.I
)

# 最小测试案例（1×1×1 单相气，秒级完成）
# 此模板已实测通过：6 时间步、0 错误、CPU <1 秒
MINIMAL_DATA_TEMPLATE = """-- Smoke test case (auto-generated by simulator_detector)
-- 1x1x1 grid, single-phase gas, single producer

RUNSPEC

TITLE
 SMOKE TEST - AUTOGEN /

DIMENS
 1 1 1 /

START
 1 'JAN' 2020 /

METRIC

GAS

WELLDIMS
 1 1 2 1 /


GRID

DX
 1000 /
DY
 1000 /
DZ
 100 /
TOPS
 2000 /

PORO
 0.20 /
PERMX
 100 /
PERMY
 100 /
PERMZ
 10 /
NTG
 1.0 /


PROPS

ROCK
 250 1.0E-5 /

-- Dry gas PVT: P, 1/Bg, visg
PVDG
 1     1.00    0.015
 50    0.020   0.015
 250   0.0040  0.025
 500   0.0020  0.025
 1000  0.0010  0.030 /

DENSITY
 850 1000 0.80 /


SOLUTION

PRESSURE
 250 /


SUMMARY

FPR
FGPR
FGPT


SCHEDULE

WELSPECS
 'P1' 'G1' 1 1 2000 'GAS' /
/

COMPDAT
 'P1' 1 1 1 1 'OPEN' 1* 10 /
/

WCONPROD
 'P1' 'OPEN' 'GRAT' 1* 1* 50000 100 1* 1* /
/

TSTEP
 5 5 5 5 /

END
"""


# ============================================================
# 数据模型
# ============================================================

@dataclass
class SimulatorInstance:
    """单个模拟器实例"""
    product: str           # ECLIPSE_100 / ECLIPSE_300 / INTERSECT / ...
    exe_path: str          # 完整可执行文件路径
    version: Optional[str] = None        # 2022.2
    build: Optional[str] = None         # 20220711.4
    arch: Optional[str] = None          # pc_x86_64 / pc_x86_64e / pc_win32
    install_root: Optional[str] = None  # C:\\ecl\\2022.2
    source: str = "unknown"            # registry / common_path / filesystem_deep / env
    file_size_mb: Optional[float] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class LicenseStatus:
    """License 状态"""
    env_vars: Dict[str, str] = field(default_factory=dict)
    server_port: Optional[int] = None
    server_host: Optional[str] = None
    license_type: Optional[str] = None  # 'network' / 'node_locked' / 'unknown'
    lmutil_path: Optional[str] = None
    lmstat_summary: Optional[str] = None
    smoke_test_results: Dict[str, dict] = field(default_factory=dict)
    overall_status: str = "unknown"     # 'ok' / 'no_license' / 'unknown'

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class DetectionReport:
    """完整检测报告"""
    scan_time: str
    hostname: str
    os_version: str
    python_version: str
    simulators: List[dict] = field(default_factory=list)
    license: dict = field(default_factory=dict)
    scan_stats: dict = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


# ============================================================
# 检测器主类
# ============================================================

class SimulatorDetector:
    """模拟器检测器"""

    def __init__(self, verbose: bool = False, deep: bool = False,
                 extra_roots: Optional[List[str]] = None):
        self.verbose = verbose
        self.deep = deep
        self.extra_roots = extra_roots or []
        self.simulators: List[SimulatorInstance] = []
        self.license = LicenseStatus()
        self.scan_stats = {
            'registry_hits': 0,
            'common_path_hits': 0,
            'filesystem_hits': 0,
            'env_hits': 0,
            'duplicate_removed': 0,
            'smoke_test_runs': 0,
            'duration_sec': 0.0,
        }
        self.warnings: List[str] = []

    def log(self, msg: str):
        if self.verbose:
            print(f"  [*] {msg}", file=sys.stderr)

    # ------------------------------------------------------------
    # 主流程
    # ------------------------------------------------------------

    def detect_all(self) -> 'SimulatorDetector':
        """执行全部检测"""
        t0 = time.time()
        self.log("=== 第 1 层：环境变量 ===")
        self._search_env()

        self.log("=== 第 2 层：注册表 ===")
        self._search_registry()

        self.log("=== 第 3 层：常见路径 ===")
        self._search_common_paths()

        if self.deep:
            self.log("=== 第 4 层：全盘深度搜索 ===")
            self._search_filesystem_deep()

        self.log("=== 去重与版本补全 ===")
        self._dedup()
        self._enrich_versions_from_path()
        self._enrich_versions_from_file_info()

        self.log("=== License 探测 ===")
        self._check_license_env()
        self._check_lmutil()

        self.scan_stats['duration_sec'] = round(time.time() - t0, 2)
        return self

    # ------------------------------------------------------------
    # 检索 1：环境变量 PATH
    # ------------------------------------------------------------

    def _search_env(self):
        """从 PATH 环境变量中查找模拟器"""
        path = os.environ.get('PATH', '')
        for p in path.split(os.pathsep):
            if not p:
                continue
            pp = Path(p)
            try:
                for exe in pp.glob('*.exe'):
                    if exe.name.lower() in TARGET_EXE_NAMES:
                        sim = self._identify_exe(exe, source='env')
                        if sim:
                            self.simulators.append(sim)
                            self.scan_stats['env_hits'] += 1
                            self.log(f"env: {exe}")
            except (PermissionError, OSError):
                continue

    # ------------------------------------------------------------
    # 检索 2：注册表
    # ------------------------------------------------------------

    def _search_registry(self):
        """查询 Windows 注册表已安装程序"""
        if not winreg:
            self.warnings.append("非 Windows 平台，跳过注册表查询")
            return

        for root, subkey in REGISTRY_UNINSTALL_KEYS:
            try:
                with winreg.OpenKey(root, subkey) as k:
                    n_sub = winreg.QueryInfoKey(k)[0]
                    for i in range(n_sub):
                        try:
                            subname = winreg.EnumKey(k, i)
                            with winreg.OpenKey(k, subname) as sk:
                                name = self._reg_get(sk, "DisplayName")
                                if not name or not REGISTRY_NAME_PATTERN.search(name):
                                    continue
                                loc = self._reg_get(sk, "InstallLocation")
                                ver = self._reg_get(sk, "DisplayVersion")
                                if loc:
                                    self.log(f"registry: {name} -> {loc}")
                                    self.scan_stats['registry_hits'] += 1
                                    self._scan_dir_for_exes(Path(loc), source='registry')
                        except OSError:
                            continue
            except OSError:
                continue

    @staticmethod
    def _reg_get(key, name: str) -> Optional[str]:
        try:
            val, _ = winreg.QueryValueEx(key, name)
            return str(val) if val else None
        except (FileNotFoundError, OSError):
            return None

    # ------------------------------------------------------------
    # 检索 3：常见安装路径
    # ------------------------------------------------------------

    def _search_common_paths(self):
        roots = list(COMMON_INSTALL_ROOTS) + list(self.extra_roots)
        for root in roots:
            p = Path(root)
            if not p.exists():
                continue
            self.log(f"common: 扫描 {p}")
            found_before = len(self.simulators)
            self._scan_dir_for_exes(p, source='common_path', maxdepth=6)
            self.scan_stats['common_path_hits'] += len(self.simulators) - found_before

    # ------------------------------------------------------------
    # 检索 4：全盘深度搜索（用 PowerShell 加速）
    # ------------------------------------------------------------

    def _search_filesystem_deep(self, drives: Optional[List[str]] = None):
        if drives is None:
            drives = ['C:', 'D:', 'E:']

        # PowerShell Get-ChildItem 比 Python os.walk 快得多
        for drive in drives:
            drive_path = Path(drive + '\\')
            if not drive_path.exists():
                continue
            self.log(f"deep: 全盘搜索 {drive}")
            try:
                # 用 PowerShell 加速
                ps_script = (
                    f"Get-ChildItem -Path '{drive}\\' -Recurse -Depth 5 -Filter '*.exe' "
                    f"-ErrorAction SilentlyContinue | "
                    f"Where-Object {{ $_.Name -match '^(eclipse|e300|intersect|ix|frontsim|visage|petrel|eclrun)(_[a-z]+)?\\.exe$' }} | "
                    f"ForEach-Object {{ $_.FullName }}"
                )
                r = subprocess.run(
                    ['powershell', '-NoProfile', '-NonInteractive', '-Command', ps_script],
                    capture_output=True, text=True, timeout=300
                )
                if r.returncode == 0:
                    for line in r.stdout.strip().split('\n'):
                        line = line.strip()
                        if not line:
                            continue
                        exe = Path(line)
                        if exe.name.lower() in TARGET_EXE_NAMES and exe.exists():
                            sim = self._identify_exe(exe, source='filesystem_deep')
                            if sim:
                                self.simulators.append(sim)
                                self.scan_stats['filesystem_hits'] += 1
                                self.log(f"deep: {exe}")
            except subprocess.TimeoutExpired:
                self.warnings.append(f"深度搜索 {drive} 超时")
            except Exception as e:
                self.warnings.append(f"深度搜索 {drive} 失败: {e}")

    # ------------------------------------------------------------
    # 通用：在目录中递归查找目标 exe
    # ------------------------------------------------------------

    def _scan_dir_for_exes(self, root: Path, source: str, maxdepth: int = 6):
        if not root.exists():
            return
        try:
            for exe in root.rglob('*.exe'):
                if exe.name.lower() in TARGET_EXE_NAMES:
                    sim = self._identify_exe(exe, source=source)
                    if sim:
                        self.simulators.append(sim)
                        self.log(f"{source}: {exe}")
        except (PermissionError, OSError):
            pass

    # ------------------------------------------------------------
    # 识别单个 exe → SimulatorInstance
    # ------------------------------------------------------------

    def _identify_exe(self, exe: Path, source: str) -> Optional[SimulatorInstance]:
        for pattern, product in PRODUCT_RULES:
            if pattern.match(exe.name):
                version, install_root, arch = self._infer_version_and_root(exe)
                try:
                    size_mb = round(exe.stat().st_size / 1024 / 1024, 2)
                except OSError:
                    size_mb = None
                return SimulatorInstance(
                    product=product,
                    exe_path=str(exe).replace('/', '\\'),
                    version=version,
                    arch=arch,
                    install_root=install_root,
                    source=source,
                    file_size_mb=size_mb,
                )
        return None

    @staticmethod
    def _infer_version_and_root(exe: Path):
        """从路径中提取版本、安装根、架构

        典型路径:
          C:\\ecl\\2022.2\\bin\\pc_x86_64\\eclipse.exe
          C:\\ecl\\2022.1\\IX\\bin\\intersect.exe
          C:\\Program Files\\Schlumberger\\Petrel 2022.2\\Petrel.exe
        """
        parts = exe.parts
        version = None
        install_root = None
        arch = None

        # 模式 1: <root>/<version>/bin/<arch>/exe
        for i, p in enumerate(parts):
            m = VERSION_PATTERN.match(p)
            if m:
                version = m.group(1)
                install_root = str(Path(*parts[:i + 1]))
                # 查找 bin 子目录下的架构
                if i + 2 < len(parts) and parts[i + 1].lower() == 'bin':
                    arch = parts[i + 2]
                break

        # 模式 2: 路径包含 "Petrel 2022.2"
        if version is None:
            for i, p in enumerate(parts):
                m = re.search(r'(\d{4}\.\d+)', p)
                if m and ('petrel' in p.lower() or 'eclipse' in p.lower() or 'schlumberger' in p.lower()):
                    version = m.group(1)
                    install_root = str(Path(*parts[:i + 1]))
                    break

        # 模式 3: 一般版本号
        if version is None:
            for p in parts:
                m = re.match(r'^(\d{4}\.\d+)$', p)
                if m:
                    version = m.group(1)
                    break

        install_root = install_root.replace('/', '\\') if install_root else None
        return version, install_root, arch

    # ------------------------------------------------------------
    # 去重
    # ------------------------------------------------------------

    def _dedup(self):
        seen = {}
        unique = []
        for sim in self.simulators:
            key = sim.exe_path.lower()
            if key in seen:
                self.scan_stats['duplicate_removed'] += 1
                # 保留信息更全的那条
                old = seen[key]
                if (sim.version and not old.version) or \
                   (sim.source == 'registry' and old.source == 'env'):
                    seen[key] = sim
            else:
                seen[key] = sim
                unique.append(sim)
        self.simulators = unique

    # ------------------------------------------------------------
    # 版本补全
    # ------------------------------------------------------------

    def _enrich_versions_from_path(self):
        for sim in self.simulators:
            if sim.version is None:
                v, _, _ = self._infer_version_and_root(Path(sim.exe_path))
                if v:
                    sim.version = v

    def _enrich_versions_from_file_info(self):
        """用 PowerShell 获取 exe 文件版本信息"""
        for sim in self.simulators:
            if sim.version is not None:
                continue
            try:
                r = subprocess.run(
                    ['powershell', '-NoProfile', '-NonInteractive', '-Command',
                     f"(Get-Item -LiteralPath '{sim.exe_path}').VersionInfo.ProductVersion"],
                    capture_output=True, text=True, timeout=10
                )
                v = r.stdout.strip()
                if v and v != '0.0.0.0':
                    sim.version = v
            except Exception:
                pass

    # ------------------------------------------------------------
    # License 探测
    # ------------------------------------------------------------

    def _check_license_env(self):
        """检查 license 环境变量"""
        for v in LICENSE_ENV_VARS:
            if v in os.environ and os.environ[v]:
                self.license.env_vars[v] = os.environ[v]

        # 解析 server 端口和主机
        for key, val in self.license.env_vars.items():
            # 格式: port@host 或 port@host[,port@host]
            m = re.match(r'(\d+)@([\w.\-]+)', val)
            if m:
                self.license.server_port = int(m.group(1))
                self.license.server_host = m.group(2)
                self.license.license_type = 'network'
                break
            elif val.startswith('28000') or '@' in val:
                # 网络版
                self.license.license_type = 'network'
            else:
                # 可能是 node-locked
                self.license.license_type = 'node_locked_or_unknown'

    def _check_lmutil(self):
        """查找 lmutil 并尝试 lmstat 查询"""
        candidates = []

        # 1. PATH 中的 lmutil
        path_lmutil = shutil.which('lmutil')
        if path_lmutil:
            candidates.append(path_lmutil)

        # 2. 常见安装位置
        guess_paths = [
            r"C:\ecl\home\lmutil.exe",
            r"C:\ecl\macros\lmutil.exe",
            r"C:\Program Files\Schlumberger\lmutil.exe",
            r"C:\Program Files (x86)\Schlumberger\lmutil.exe",
            r"C:\Program Files\FLEXlm\lmutil.exe",
        ]
        # 3. 从已发现的模拟器路径推断
        for sim in self.simulators:
            if sim.install_root:
                guess_paths.append(str(Path(sim.install_root) / 'bin' / 'lmutil.exe'))
                guess_paths.append(str(Path(sim.install_root) / 'home' / 'lmutil.exe'))

        for c in guess_paths:
            if c and Path(c).exists():
                candidates.append(c)

        # 去重
        seen = set()
        uniq = []
        for c in candidates:
            cl = c.lower()
            if cl not in seen:
                seen.add(cl)
                uniq.append(c)
        candidates = uniq

        for c in candidates:
            if not Path(c).exists():
                continue
            self.license.lmutil_path = c
            self.log(f"lmutil: {c}")

            # 尝试 lmstat
            if self.license.env_vars:
                lic = list(self.license.env_vars.values())[0]
                try:
                    r = subprocess.run(
                        [c, 'lmstat', '-c', lic, '-a'],
                        capture_output=True, text=True, timeout=15
                    )
                    out = r.stdout + r.stderr
                    # 截取关键摘要
                    summary_lines = []
                    for line in out.split('\n'):
                        if any(k in line.lower() for k in
                               ['server', 'license', 'feature', 'error', 'up', 'down',
                                'vendor', 'daemon', 'conn']):
                            summary_lines.append(line.strip())
                    self.license.lmstat_summary = '\n'.join(summary_lines[:30]) or out[:1500]
                except subprocess.TimeoutExpired:
                    self.warnings.append("lmutil lmstat 查询超时")
                except Exception as e:
                    self.warnings.append(f"lmutil 查询失败: {e}")
            break  # 用第一个找到的 lmutil 即可

    # ------------------------------------------------------------
    # Smoke test：最小测试案例
    # ------------------------------------------------------------

    def run_smoke_tests(self, products: Optional[List[str]] = None) -> Dict[str, dict]:
        """对所有模拟器实例跑 smoke test

        products: 限定产品列表，如 ['ECLIPSE_100', 'ECLIPSE_300']。
                  None 表示全部支持 smoke test 的产品。
        """
        supported = {'ECLIPSE_100', 'ECLIPSE_300'}  # smoke test 当前只支持这两个
        if products:
            supported = set(products) & supported

        results: Dict[str, dict] = {}
        for sim in self.simulators:
            if sim.product not in supported:
                continue
            # 同一 exe 只测一次
            key = sim.exe_path.lower()
            if key in results:
                continue
            self.log(f"smoke test: {sim.product} @ {sim.exe_path}")
            result = self._smoke_test_one(sim)
            results[key] = result
            self.scan_stats['smoke_test_runs'] += 1
            # 更新 license 总体状态
            # 关键判据：license 是否被拒绝（不是案例本身错误）
            if result.get('error') == 'license_denied':
                self.license.overall_status = 'no_license'
            elif result.get('ok'):
                # 完整通过
                if self.license.overall_status != 'no_license':
                    self.license.overall_status = 'ok'
            elif result.get('error', '').startswith('case_errors_'):
                # 案例错误但 license 通过了（能跑到 simulation 阶段）
                if self.license.overall_status != 'no_license':
                    self.license.overall_status = 'ok'
            elif result.get('error') in ('no_prt_file', 'no_ecle_end'):
                # 没生成 PRT/ECLEND → 可能是 license 问题或环境问题
                if self.license.overall_status != 'no_license':
                    self.license.overall_status = 'unknown'

        self.license.smoke_test_results = results
        return results

    def _smoke_test_one(self, sim: SimulatorInstance) -> dict:
        """运行最小测试案例"""
        result = {
            'product': sim.product,
            'exe_path': sim.exe_path,
            'ok': False,
            'duration_sec': 0.0,
            'returncode': None,
            'error': None,
            'prt_head': None,
            'outputs': [],
            'extracted_version': None,
            'extracted_build': None,
        }

        if not Path(sim.exe_path).exists():
            result['error'] = 'exe_not_found'
            return result

        with tempfile.TemporaryDirectory(prefix='ecl_smoke_') as td:
            td_path = Path(td)
            case_name = 'SMOKE'
            (td_path / f'{case_name}.DATA').write_text(
                MINIMAL_DATA_TEMPLATE, encoding='utf-8'
            )

            # 准备环境变量
            env = os.environ.copy()
            if 'SLBSLS_LICENSE_FILE' not in env:
                # 注入检测到的 license
                for v in LICENSE_ENV_VARS:
                    if v in self.license.env_vars:
                        env[v] = self.license.env_vars[v]
                        break

            t0 = time.time()
            try:
                r = subprocess.run(
                    [sim.exe_path, case_name],
                    cwd=str(td_path),
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=120,
                )
                result['duration_sec'] = round(time.time() - t0, 2)
                result['returncode'] = r.returncode

                # 解析 .PRT
                prt = td_path / f'{case_name}.PRT'
                if prt.exists():
                    head = prt.read_text(encoding='latin-1', errors='ignore')[:1500]
                    result['prt_head'] = head

                    # 检查 license 关键字（优先判断）
                    head_lower = head.lower()
                    if 'no license' in head_lower or 'flexlm error' in head_lower or \
                       'license error' in head_lower or 'cannot get license' in head_lower:
                        result['error'] = 'license_denied'
                    else:
                        # 提取版本和构建号
                        m = PRT_VERSION_PATTERN.search(head)
                        if m:
                            result['extracted_version'] = m.group(1)
                            if m.group(2):
                                result['extracted_build'] = m.group(2)
                            # 同步回 simulator
                            if not sim.version:
                                sim.version = result['extracted_version']
                            sim.build = result['extracted_build']

                    # 从 PRT 末尾提取错误/警告数（更稳健的判断）
                    try:
                        full_prt = prt.read_text(encoding='latin-1', errors='ignore')
                        # 匹配 " Errors  N" 或 "Errors                 N"
                        err_match = re.search(
                            r'^\s*Errors?\s+(\d+)\s*$', full_prt, re.MULTILINE | re.IGNORECASE
                        )
                        result['error_count_in_prt'] = int(err_match.group(1)) if err_match else None
                    except Exception:
                        result['error_count_in_prt'] = None

                    # 输出文件列表
                    outputs = sorted(f.name for f in td_path.glob(f'{case_name}.*'))
                    result['outputs'] = outputs

                    # 判断成功（三层判据）
                    ecle = td_path / f'{case_name}.ECLEND'
                    has_ecle = ecle.exists()

                    if result['error'] == 'license_denied':
                        pass  # 已设
                    elif not has_ecle:
                        result['error'] = 'no_ecle_end'
                    elif result.get('error_count_in_prt', -1) == 0:
                        result['ok'] = True
                    elif result.get('error_count_in_prt', -1) and result['error_count_in_prt'] > 0:
                        result['error'] = f'case_errors_{result["error_count_in_prt"]}'
                    else:
                        # 兜底：有 ECLEND 且无 license error，认为通过
                        result['ok'] = True
                else:
                    # .PRT 没生成 → license 失败可能性大
                    if 'license' in (r.stdout + r.stderr).lower():
                        result['error'] = 'license_denied'
                    else:
                        result['error'] = 'no_prt_file'

            except subprocess.TimeoutExpired:
                result['duration_sec'] = 120.0
                result['error'] = 'timeout'
            except Exception as e:
                result['error'] = f'exception: {e}'
                result['duration_sec'] = round(time.time() - t0, 2)

        return result


# ============================================================
# 报告生成
# ============================================================

def format_text_report(report: DetectionReport) -> str:
    """生成可读文本报告"""
    lines = []
    sep = '=' * 72

    lines.append(sep)
    lines.append("  Schlumberger 油藏模拟器检测报告")
    lines.append(sep)
    lines.append(f"  扫描时间 : {report.scan_time}")
    lines.append(f"  主机名   : {report.hostname}")
    lines.append(f"  操作系统 : {report.os_version}")
    lines.append(f"  Python   : {report.python_version}")
    lines.append(f"  扫描耗时 : {report.scan_stats.get('duration_sec', 0)} 秒")
    lines.append("")

    # ---- 模拟器列表 ----
    lines.append(sep)
    lines.append("  一、模拟器检测结果")
    lines.append(sep)
    if not report.simulators:
        lines.append("  未检测到任何 Schlumberger 模拟器。")
        lines.append("  建议：")
        lines.append("    1. 检查软件是否已安装")
        lines.append("    2. 使用 --deep 参数进行全盘深度搜索")
        lines.append("    3. 使用 --extra-root <path> 添加自定义搜索根")
    else:
        lines.append(f"  共检测到 {len(report.simulators)} 个模拟器实例：")
        lines.append("")
        # 按产品分组
        by_product: Dict[str, List[dict]] = {}
        for s in report.simulators:
            by_product.setdefault(s['product'], []).append(s)

        product_order = ['ECLIPSE_100', 'ECLIPSE_300', 'INTERSECT',
                         'FRONTSIM', 'VISAGE', 'PETREL', 'ECLRUN']
        for product in product_order:
            if product not in by_product:
                continue
            instances = by_product[product]
            lines.append(f"  [{product}]  ({len(instances)} 个)")
            for i, s in enumerate(instances, 1):
                lines.append(f"    #{i} {s['exe_path']}")
                lines.append(f"        版本   : {s.get('version') or '未知'}"
                             + (f" (Build {s['build']})" if s.get('build') else ""))
                lines.append(f"        架构   : {s.get('arch') or '-'}")
                lines.append(f"        安装根 : {s.get('install_root') or '-'}")
                lines.append(f"        来源   : {s.get('source', 'unknown')}"
                             + (f"  大小: {s['file_size_mb']} MB" if s.get('file_size_mb') else ""))
            lines.append("")

    # ---- License 状态 ----
    lines.append(sep)
    lines.append("  二、License 状态")
    lines.append(sep)
    lic = report.license
    if lic.get('overall_status') == 'ok':
        lines.append(f"  总体状态 : OK (绿色)")
    elif lic.get('overall_status') == 'no_license':
        lines.append(f"  总体状态 : License 不可用 (红色)")
    else:
        lines.append(f"  总体状态 : 未知 (建议运行 smoke test 验证)")

    lines.append("")
    lines.append("  环境变量：")
    if lic.get('env_vars'):
        for k, v in lic['env_vars'].items():
            lines.append(f"    {k} = {v}")
    else:
        lines.append("    (无 license 相关环境变量)")

    if lic.get('server_host') or lic.get('server_port'):
        lines.append("")
        lines.append(f"  License Server : {lic.get('server_port')}@{lic.get('server_host')}")
        lines.append(f"  License 类型   : {lic.get('license_type', 'unknown')}")

    lines.append("")
    lines.append(f"  lmutil 路径 : {lic.get('lmutil_path') or '(未找到)'}")
    if lic.get('lmstat_summary'):
        lines.append("")
        lines.append("  lmstat 摘要：")
        for line in lic['lmstat_summary'].split('\n')[:15]:
            lines.append(f"    {line}")

    # ---- Smoke test 结果 ----
    if lic.get('smoke_test_results'):
        lines.append("")
        lines.append(sep)
        lines.append("  三、Smoke Test 验证结果")
        lines.append(sep)
        for key, res in lic['smoke_test_results'].items():
            status = "PASS" if res.get('ok') else "FAIL"
            icon = "[OK]" if res.get('ok') else "[X]"
            lines.append(f"  {icon} {res.get('product')} @ {key}")
            lines.append(f"      状态      : {status}")
            lines.append(f"      耗时      : {res.get('duration_sec', 0)} 秒")
            lines.append(f"      退出码    : {res.get('returncode')}")
            if res.get('error'):
                lines.append(f"      错误      : {res['error']}")
            if res.get('error_count_in_prt') is not None:
                lines.append(f"      PRT错误数: {res['error_count_in_prt']}")
            if res.get('extracted_version'):
                lines.append(f"      版本(PRT) : {res['extracted_version']}"
                             + (f" Build {res['extracted_build']}" if res.get('extracted_build') else ""))
            if res.get('outputs'):
                lines.append(f"      输出文件  : {', '.join(res['outputs'])}")

    # ---- 警告 ----
    if report.warnings:
        lines.append("")
        lines.append(sep)
        lines.append("  四、警告")
        lines.append(sep)
        for w in report.warnings:
            lines.append(f"  [!] {w}")

    # ---- 扫描统计 ----
    lines.append("")
    lines.append(sep)
    lines.append("  五、扫描统计")
    lines.append(sep)
    for k, v in report.scan_stats.items():
        lines.append(f"  {k:25s} : {v}")

    lines.append("")
    lines.append(sep)
    lines.append("  报告结束")
    lines.append(sep)
    return '\n'.join(lines)


def format_json_report(report: DetectionReport) -> str:
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False)


# ============================================================
# 主入口
# ============================================================

def build_report(detector: SimulatorDetector) -> DetectionReport:
    return DetectionReport(
        scan_time=time.strftime('%Y-%m-%d %H:%M:%S'),
        hostname=socket.gethostname(),
        os_version=platform.platform(),
        python_version=sys.version.split()[0],
        simulators=[s.to_dict() for s in detector.simulators],
        license=detector.license.to_dict(),
        scan_stats=detector.scan_stats,
        warnings=detector.warnings,
    )


def main():
    parser = argparse.ArgumentParser(
        description='Schlumberger 油藏模拟器自动识别与 License 验证工具',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s                          标准检测
  %(prog)s --deep                   全盘深度搜索
  %(prog)s --no-smoke               跳过 smoke test
  %(prog)s --extra-root D:\\MySLB   添加自定义搜索根
  %(prog)s -v                       详细模式
        """
    )
    parser.add_argument('--deep', action='store_true',
                        help='启用全盘深度搜索（较慢，但能发现非标准路径的安装）')
    parser.add_argument('--no-smoke', action='store_true',
                        help='跳过 smoke test 验证（只检测 license 环境变量和 lmutil）')
    parser.add_argument('--only-smoke', metavar='PRODUCT',
                        help='只对指定产品跑 smoke test (ECLIPSE_100 / ECLIPSE_300)')
    parser.add_argument('--extra-root', action='append', default=[],
                        metavar='PATH', help='添加自定义搜索根目录（可多次指定）')
    parser.add_argument('--out', default='.',
                        help='报告输出目录 (默认当前目录)')
    parser.add_argument('--json', action='store_true',
                        help='输出 JSON 到终端')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='详细输出（显示检索过程）')
    args = parser.parse_args()

    print(">>> 开始检测 Schlumberger 模拟器...", file=sys.stderr)
    detector = SimulatorDetector(
        verbose=args.verbose,
        deep=args.deep,
        extra_roots=args.extra_root,
    )
    detector.detect_all()

    if not args.no_smoke:
        products = [args.only_smoke] if args.only_smoke else None
        print(">>> 运行 smoke test...", file=sys.stderr)
        detector.run_smoke_tests(products=products)

    report = build_report(detector)

    out_dir = Path(args.out).absolute()
    out_dir.mkdir(parents=True, exist_ok=True)
    txt_path = out_dir / 'simulator_report.txt'
    json_path = out_dir / 'simulator_report.json'
    txt_path.write_text(format_text_report(report), encoding='utf-8')
    json_path.write_text(format_json_report(report), encoding='utf-8')

    if args.json:
        print(format_json_report(report))
    else:
        print(format_text_report(report))

    print(f"\n>>> 文本报告: {txt_path}", file=sys.stderr)
    print(f">>> JSON 报告: {json_path}", file=sys.stderr)
    print(f">>> 共检测到 {len(report.simulators)} 个模拟器", file=sys.stderr)


if __name__ == '__main__':
    main()
